### ISSUE TITLE
create deployment checklist

### ISSUE THREAD

**Issue by xh3b4sd** [uvio-network/issues#23]
- [ ] Configure blockchain RPC endpoints so that the `webclient` and the `apiserver` can interact with the chain. Our RPC provider is [Alchemy](https://www.alchemy.com) at the moment, where we have e.g. API keys for Base Sepolia configured.
- [ ] Configure paymasters for account abstraction and gas sponsorship. We are currently using [Biconomy](https://biconomy.io) and have gas tanks and smart contract rules configured for e.g. Base Sepolia. Here we can restrict what types of requests and actions we are paying gas for.
- [ ] Configure auth providers for user management. The auth provider we are using right now is [Privy](https://www.privy.io). Here we need to setup an API key and get a JWK URL. The JWK URL, the issuer `privy.io` and the audience (privy API key), must be configured in the `apiserver` in order to make authenticated requests work between the `webclient` and the `apiserver`.
- [ ] Deploy smart contracts onchain. The deployment scripts are in the [Contracts](https://github.com/uvio-network/contracts) repository and the currently applied documentation can be found at https://docs.uvio.network/contracts/base-sepolia.
  - [ ] Update smart contract ownership for production deployments. On testnet the deployer is currently the owner, which, momentarily, is frankly good enough to start with.
  - [ ] Grant roles to privileged accounts. 
    - [ ] The `BOT_ROLE` needs to be granted to the `Apiserver Signer` in the `UVX` contract for minting tokens for new users.
    - [ ] The `BOT_ROLE` needs to be granted to the `Apiserver Signer` in the `Claims` contract for creating resolves automatically.
    - [ ] `LOAN_ROLE`
    - [ ] The `CONTRACT_ROLE` needs to be granted to the `Claims` contract in the `UVX` contract for transfers to be allowed.
    - [ ] The `TOKEN_ROLE` role needs to be granted to any token contract like `USDC` in order to be used as collateral in the `UVX` contract.
- [ ] Deploy web services. All web services are currently deployed on [Render](https://render.com). DNS is covered by [Cloudflare](https://cloudflare.com).
  - [ ] The `webclient` repository can simply be linked. Render detects a NextJs app and everything works pretty much out of the box. The `env.local` secret file needs to be configured properly with e.g. the correct Chain ID and privy credentials etc. Render requires the `PORT` env var to be set, for NextJs that is `3000`.
  - [ ] The `apiserver` repository can simply be linked. Render detects a Go app and everything works pretty much out of the box. The `env.sepolia` secret file needs to be configured properly with the app command `./apiserver daemon --env sepolia`. The secret env file contains e.g. the smart contract addresses and RPC endpoint. Render requires the `PORT` env var to be set, for Twirp that is `7777`.

Following these instructions we should get https://testnet.uvio.network up online.
